version: "3"
services:
  api:
    image: esaude-docker-esaude-admin.bintray.io/esaude-admin-api:0.1.0-alpha1
    hostname: esaude-admin-api
    container_name: esaude-admin-api
    networks:
      - network
    ports:
      - "2580:2580"
    volumes:
      - data:/opt/esaude/data
      - /var/run/docker.sock:/var/run/docker.sock
  web:
    image: esaude-docker-esaude-admin.bintray.io/esaude-admin-web:0.1.0-alpha1
    hostname: esaude-admin-web
    container_name: esaude-admin-web
    networks:
      - network
    ports:
      - "2581:80"
    volumes:
      - data:/opt/esaude/data
networks:
  network:
volumes:
  data:
